export { default as HomePage } from './Home/Home'
export { default as MovieListPage } from './Movies/MovieList'
export { default as MovieDetailPage } from './Movies/MovieDetail'
export { default as BookmarkPage } from './Bookmark/Bookmark'
export { default as PageNotFound } from './PageNotFound/PageNotFound'
export { default as DemoPage } from './Demonstration/Demonstration'
